version: '3.7'
services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=changeme
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: .
    image: rails-on-docker:1.3.0
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      - DATABASE_URL=postgres://postgres:changeme@db
      - WEBPACKER_DEV_SERVER_HOST=webpacker
      - BOOTSNAP_CACHE_DIR=/usr/local/bundle/_bootsnap
      - WEB_CONCURRENCY=1
      - HISTFILE=/usr/src/app/.dockerdev/.bash_history
      - MALLOC_ARENA_MAX=2
      - REDIS_URL_CACHING=redis://redis:6379/0
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
      - REDIS_URL=redis://redis:6379/1
    volumes:
      - .:/usr/src/app/:cached
      - bundle:/usr/local/bundle
      - rails_cache:/usr/src/app/tmp/cache
      - node_modules:/usr/src/app/node_modules
      - packs:/usr/src/app/public/packs
    depends_on:
      - db
      - redis
  webpacker:
    build: .
    image: rails-on-docker:1.3.0
    command: ./bin/webpack-dev-server
    ports:
      - "3035:3035"
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
      - MALLOC_ARENA_MAX=2
    volumes:
      - .:/usr/src/app:cached
      - bundle:/usr/local/bundle
      - node_modules:/usr/src/app/node_modules
      - packs:/usr/src/app/public/packs
  redis:
    image: redis:latest
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    #image: 'redis:5-alpine'
    #command: redis-server
    #ports:
    #  - '6379:6379'
    #volumes:
    #  - 'redis:/data'
  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/usr/src/app
      - '/usr/src/app/tmp' # don't mount tmp directory
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
volumes:
  bundle:
  db_data:
  node_modules:
  rails_cache:
  packs:
  redis:
